import js from '@eslint/js';
import prettier from 'eslint-config-prettier';
import globals from 'globals';

// ES modules, but for the code that stays CommonJS: ported upstream code (@xufa/openapi, the library of @xufa/yaml)
// and the packages of the repository whose package.json says so (bench, tools with a package of their own).
const COMMONJS = [
  'packages/openapi/**/*.js',
  'packages/yaml/**/*.js',
  'bench/**/*.js',
  'tools/fastify-plugins/**/*.js',
  'tools/node-test-to-vyntra/**/*.js',
  'tools/sequelize-compat/**/*.js',
  '**/*.cjs',
];

export default [
  {
    // The tests are ported from upstream projects (generated by tools/node-test-to-vyntra) and keep their style.
    ignores: [
      '**/node_modules/**',
      'packages/*/test/**',
      'bench/results/**',
      'docs/**',
      'tools/sequelize-compat/test/**',
      'tools/sequelize-compat/.snapshot/**',
      // js-yaml 4.1.0 as it is (tools/port-yaml): its style is kept, so it can be ported again.
      'packages/yaml/lib/**',
      // The built page of the admin (client/build.js).
      'packages/admin/lib/client/dist/**',
    ],
  },
  { linterOptions: { reportUnusedDisableDirectives: 'off' } },
  js.configs.recommended,
  prettier,
  {
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: { ...globals.node },
    },
    rules: {
      'no-unused-vars': [
        'error',
        { args: 'after-used', argsIgnorePattern: '^_', caughtErrors: 'none', ignoreRestSiblings: true },
      ],
      // Code may declare what Node also gives (FormData of undici, localStorage of a page).
      'no-redeclare': ['error', { builtinGlobals: false }],
    },
  },
  {
    files: COMMONJS,
    languageOptions: { sourceType: 'commonjs', globals: { ...globals.node, ...globals.commonjs } },
  },
  {
    // The page of the admin: React (JSX) in the browser, bundled by packages/admin/client/build.js.
    files: ['packages/admin/client/src/**/*.{js,jsx}'],
    languageOptions: {
      sourceType: 'module',
      parserOptions: { ecmaFeatures: { jsx: true } },
      globals: { ...globals.browser },
    },
    rules: {
      // Components are used in JSX, which the rule does not see.
      'no-unused-vars': ['error', { varsIgnorePattern: '^[A-Z]', args: 'after-used', argsIgnorePattern: '^_' }],
    },
  },
];
