const js = require('@eslint/js');
const prettier = require('eslint-config-prettier');

module.exports = [
  {
    // The tests are ported from upstream projects (generated by tools/node-test-to-vyntra) and keep their style.
    ignores: [
      '**/node_modules/**',
      'packages/*/test/**',
      'bench/results/**',
      'docs/**',
      'tools/sequelize-compat/test/**',
      'tools/sequelize-compat/.snapshot/**',
      // js-yaml 4.1.0 as it is (tools/port-yaml): its style is kept, so it can be ported again.
      'packages/yaml/lib/**',
    ],
  },
  { linterOptions: { reportUnusedDisableDirectives: 'off' } },
  js.configs.recommended,
  prettier,
  {
    languageOptions: {
      ecmaVersion: 2024,
      sourceType: 'commonjs',
      globals: {
        require: 'readonly',
        module: 'writable',
        exports: 'writable',
        __dirname: 'readonly',
        __filename: 'readonly',
        process: 'readonly',
        Buffer: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        setImmediate: 'readonly',
        clearImmediate: 'readonly',
        queueMicrotask: 'readonly',
        structuredClone: 'readonly',
        AbortController: 'readonly',
        AbortSignal: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        performance: 'readonly',
        fetch: 'readonly',
        globalThis: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': [
        'error',
        { args: 'after-used', argsIgnorePattern: '^_', caughtErrors: 'none', ignoreRestSiblings: true },
      ],
    },
  },
  {
    files: ['**/*.mjs'],
    languageOptions: { sourceType: 'module' },
  },
];
