// @xufa/schema: schemas of data. Written as code with s (plain JSON Schemas, with their TypeScript types), as JSON
// Schema (draft-04 to 2020-12), or with the builder of types (new Schema({ name: String() })); compiled into
// functions that check values (the validator of the routes of @xufa/http), written as standalone code, or inferred
// from samples. No dependencies.
//
//   import { s, compileJsonSchema } from '@xufa/schema';
//   const Book = s.object({ title: s.string({ minLength: 1 }), pages: s.optional(s.integer({ minimum: 1 })) });
//   const validate = compileJsonSchema(Book);
//   validate({ pages: 0 }); // ['title is mandatory', 'pages must be at least 1']
import { ClosedSchema } from './lib/closed-schema.js';
import { compileErrors, compileFirstError, compileIsValid, compileType } from './lib/compile.js';
import {
  fromJsonSchema,
  compileJsonSchema,
  compileJsonSchemaAsync,
  loadJsonSchemas,
  builtInFormats,
} from './lib/json-schema.js';
import { Schema } from './lib/schema.js';
import { standaloneCode, standaloneModule, standaloneJsonSchema } from './lib/standalone.js';
import { ajvKeywords } from './lib/ajv-keywords.js';
import { inferJsonSchema, inferSchemaCode } from './lib/infer.js';
// The builder: JSON Schemas written as code (s.object(), s.string()...), with their types.
import { s, isOptional, OPTIONAL } from './lib/builder.js';
import {
  AllOfType,
  AllOf,
  allOf,
  oallOf,
  AnyType,
  Any,
  any,
  oany,
  AnyOfType,
  AnyOf,
  anyOf,
  oanyOf,
  ArrayOfType,
  ArrayOf,
  arrOf,
  oarrOf,
  BooleanType,
  Boolean,
  bool,
  obool,
  ConditionalType,
  Conditional,
  EnumType,
  Enum,
  enumt,
  oenumt,
  oenum,
  FloatType,
  Float,
  float,
  ofloat,
  num,
  onum,
  IntegerType,
  Integer,
  int,
  oint,
  NeverType,
  Never,
  never,
  NotType,
  Not,
  not,
  onot,
  ObjType,
  Obj,
  obj,
  oobj,
  OneOfType,
  OneOf,
  oneOf,
  ooneOf,
  RefType,
  Ref,
  StringType,
  String,
  str,
  ostr,
  ValidateType,
  hasErrors,
  toErrors,
  ValuesType,
  Values,
  Const,
  WhenType,
  When,
  isJsonType,
  KeywordType,
} from './lib/types/index.js';

export {
  s,
  isOptional,
  OPTIONAL,
  ClosedSchema,
  compileErrors,
  compileFirstError,
  compileIsValid,
  compileType,
  fromJsonSchema,
  compileJsonSchema,
  compileJsonSchemaAsync,
  loadJsonSchemas,
  Schema,
  AllOfType,
  AllOf,
  allOf,
  oallOf,
  AnyType,
  Any,
  any,
  oany,
  AnyOfType,
  AnyOf,
  anyOf,
  oanyOf,
  ArrayOfType,
  ArrayOf,
  arrOf,
  oarrOf,
  BooleanType,
  Boolean,
  bool,
  obool,
  ConditionalType,
  Conditional,
  EnumType,
  Enum,
  enumt,
  oenumt,
  oenum,
  FloatType,
  Float,
  float,
  ofloat,
  num,
  onum,
  IntegerType,
  Integer,
  int,
  oint,
  NeverType,
  Never,
  never,
  NotType,
  Not,
  not,
  onot,
  ObjType,
  Obj,
  obj,
  oobj,
  OneOfType,
  OneOf,
  oneOf,
  ooneOf,
  RefType,
  Ref,
  StringType,
  String,
  str,
  ostr,
  ValidateType,
  hasErrors,
  toErrors,
  ValuesType,
  Values,
  Const,
  WhenType,
  When,
  isJsonType,
  standaloneCode,
  standaloneModule,
  standaloneJsonSchema,
  KeywordType,
  ajvKeywords,
  builtInFormats,
  inferJsonSchema,
  inferSchemaCode,
};
