'use strict';

// @xufa/schema: schemas of data. Written as code with s (plain JSON Schemas, with their TypeScript types), as JSON
// Schema (draft-04 to 2020-12), or with the builder of types (new Schema({ name: String() })); compiled into
// functions that check values (the validator of the routes of @xufa/http), written as standalone code, or inferred
// from samples. No dependencies.
//
//   const { s, compileJsonSchema } = require('@xufa/schema');
//   const Book = s.object({ title: s.string({ minLength: 1 }), pages: s.optional(s.integer({ minimum: 1 })) });
//   const validate = compileJsonSchema(Book);
//   validate({ pages: 0 }); // ['title is mandatory', 'pages must be at least 1']
const { ClosedSchema } = require('./lib/closed-schema');
const { compileErrors, compileFirstError, compileIsValid, compileType } = require('./lib/compile');
const {
  fromJsonSchema,
  compileJsonSchema,
  compileJsonSchemaAsync,
  loadJsonSchemas,
  builtInFormats,
} = require('./lib/json-schema');
const { Schema } = require('./lib/schema');
const { standaloneCode, standaloneModule, standaloneJsonSchema } = require('./lib/standalone');
const { ajvKeywords } = require('./lib/ajv-keywords');
const { inferJsonSchema, inferSchemaCode } = require('./lib/infer');
// The builder: JSON Schemas written as code (s.object(), s.string()...), with their types.
const { s, isOptional, OPTIONAL } = require('./lib/builder');
const {
  AllOfType,
  AllOf,
  allOf,
  oallOf,
  AnyType,
  Any,
  any,
  oany,
  AnyOfType,
  AnyOf,
  anyOf,
  oanyOf,
  ArrayOfType,
  ArrayOf,
  arrOf,
  oarrOf,
  BooleanType,
  Boolean,
  bool,
  obool,
  ConditionalType,
  Conditional,
  EnumType,
  Enum,
  enumt,
  oenumt,
  oenum,
  FloatType,
  Float,
  float,
  ofloat,
  num,
  onum,
  IntegerType,
  Integer,
  int,
  oint,
  NeverType,
  Never,
  never,
  NotType,
  Not,
  not,
  onot,
  ObjType,
  Obj,
  obj,
  oobj,
  OneOfType,
  OneOf,
  oneOf,
  ooneOf,
  RefType,
  Ref,
  StringType,
  String,
  str,
  ostr,
  ValidateType,
  hasErrors,
  toErrors,
  ValuesType,
  Values,
  Const,
  WhenType,
  When,
  isJsonType,
  KeywordType,
} = require('./lib/types');

module.exports = {
  s,
  isOptional,
  OPTIONAL,
  ClosedSchema,
  compileErrors,
  compileFirstError,
  compileIsValid,
  compileType,
  fromJsonSchema,
  compileJsonSchema,
  compileJsonSchemaAsync,
  loadJsonSchemas,
  Schema,
  AllOfType,
  AllOf,
  allOf,
  oallOf,
  AnyType,
  Any,
  any,
  oany,
  AnyOfType,
  AnyOf,
  anyOf,
  oanyOf,
  ArrayOfType,
  ArrayOf,
  arrOf,
  oarrOf,
  BooleanType,
  Boolean,
  bool,
  obool,
  ConditionalType,
  Conditional,
  EnumType,
  Enum,
  enumt,
  oenumt,
  oenum,
  FloatType,
  Float,
  float,
  ofloat,
  num,
  onum,
  IntegerType,
  Integer,
  int,
  oint,
  NeverType,
  Never,
  never,
  NotType,
  Not,
  not,
  onot,
  ObjType,
  Obj,
  obj,
  oobj,
  OneOfType,
  OneOf,
  oneOf,
  ooneOf,
  RefType,
  Ref,
  StringType,
  String,
  str,
  ostr,
  ValidateType,
  hasErrors,
  toErrors,
  ValuesType,
  Values,
  Const,
  WhenType,
  When,
  isJsonType,
  standaloneCode,
  standaloneModule,
  standaloneJsonSchema,
  KeywordType,
  ajvKeywords,
  builtInFormats,
  inferJsonSchema,
  inferSchemaCode,
};
