'use strict'


const Fastify = require('..')

test('register', async () => {
  expect.assertions(16)

  const fastify = Fastify()

  fastify.register(function (instance, opts, done) {
    expect(instance).not.toBe(fastify)
    expect(Object.prototype.isPrototypeOf.call(fastify, instance)).toBeTruthy()

    expect(typeof opts).toBe('object')
    expect(typeof done).toBe('function')

    instance.get('/first', function (req, reply) {
      reply.send({ hello: 'world' })
    })
    done()
  })

  fastify.register(function (instance, opts, done) {
    expect(instance).not.toBe(fastify)
    expect(Object.prototype.isPrototypeOf.call(fastify, instance)).toBeTruthy()

    expect(typeof opts).toBe('object')
    expect(typeof done).toBe('function')

    instance.get('/second', function (req, reply) {
      reply.send({ hello: 'world' })
    })
    done()
  })

  const fastifyServer = await fastify.listen({ port: 0 })
  onTestFinished(() => fastify.close())

  await makeRequest('first')
  await makeRequest('second')

  async function makeRequest (path) {
    const response = await fetch(fastifyServer + '/' + path)
    expect(response.ok).toBeTruthy()
    expect(response.status).toBe(200)
    const body = await response.text()
    expect(response.headers.get('content-length')).toBe('' + body.length)
    expect(JSON.parse(body)).toEqual({ hello: 'world' })
  }
})

test('internal route declaration should pass the error generated by the register to the done handler / 1', (done) => {
  expect.assertions(1)
  const fastify = Fastify()

  fastify.register((instance, opts, done) => {
    done(new Error('kaboom'))
  })

  fastify.get('/', (req, reply) => {
    reply.send({ hello: 'world' })
  })

  fastify.listen({ port: 0 }, err => {
    onTestFinished(() => fastify.close())
    expect(err.message).toBe('kaboom')
    done()
  })
})

test('internal route declaration should pass the error generated by the register to the done handler / 2', (done) => {
  expect.assertions(2)
  const fastify = Fastify()

  fastify.register((instance, opts, done) => {
    done(new Error('kaboom'))
  })

  fastify.get('/', (req, reply) => {
    reply.send({ hello: 'world' })
  })

  fastify.after(err => {
    expect(err.message).toBe('kaboom')
  })

  fastify.listen({ port: 0 }, err => {
    onTestFinished(() => fastify.close())
    expect(err).toBeFalsy()
    done()
  })
})

test('awaitable register and after', async () => {
  const fastify = Fastify()
  let first = false
  let second = false
  let third = false

  await fastify.register(async (instance, opts) => {
    first = true
  })

  expect(first).toBe(true)

  fastify.register(async (instance, opts) => {
    second = true
  })

  await fastify.after()
  expect(second).toBe(true)

  fastify.register(async (instance, opts) => {
    third = true
  })

  await fastify.ready()
  expect(third).toBe(true)
})

function thenableRejects (t, promise, error) {
  return expect((async () => { await promise })()).rejects.toThrow(error)
}

test('awaitable register error handling', async (ctx) => {
  const fastify = Fastify()

  const e = new Error('kaboom')

  await thenableRejects(ctx, fastify.register(async (instance, opts) => {
    throw e
  }), e)

  fastify.register(async (instance, opts) => {
    expect.fail('should not be executed')
  })

  await expect(fastify.after()).rejects.toThrow(e)

  fastify.register(async (instance, opts) => {
    expect.fail('should not be executed')
  })

  await thenableRejects(ctx, fastify.ready(), e)
})

test('awaitable after error handling', async () => {
  const fastify = Fastify()

  const e = new Error('kaboom')

  fastify.register(async (instance, opts) => {
    throw e
  })

  fastify.register(async (instance, opts) => {
    expect.fail('should not be executed')
  })

  await expect(fastify.after()).rejects.toThrow(e)

  fastify.register(async (instance, opts) => {
    expect.fail('should not be executed')
  })

  await expect(fastify.ready()).rejects.toThrow()
})

test('chainable register', async () => {
  expect.assertions(3)

  const fastify = Fastify()

  fastify.register(async () => {
    expect('first loaded').toBeTruthy()
  }).register(async () => {
    expect('second loaded').toBeTruthy()
  }).register(async () => {
    expect('third loaded').toBeTruthy()
  })

  await fastify.ready()
})
