# Generated by Django 6.1.2 on 2026-10-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_genre_genre_name_case_insensitive_unique_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title', 'author'], name='catalog_boo_title_5b6232_idx'),
        ),
    ]
