# Generated by Django 6.1.2 on 2026-10-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_book_title_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='book',
            name='catalog_boo_title_5b6232_idx',
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title', 'author'], include=('id',), name='catalog_book_title_keys'),
        ),
    ]
