// Symbols of the internal state of instances, requests, replies and route contexts.
const names = [
  'kBoot',
  'kChildren',
  'kServerBindings',
  'kBodyLimit',
  'kSupportedHTTPMethods',
  'kRoutePrefix',
  'kLogLevel',
  'kLogSerializers',
  'kHooks',
  'kContentTypeParser',
  'kState',
  'kOptions',
  'kPluginNameChain',
  'kRouteContext',
  'kGenReqId',
  'kHttp2ServerSessions',
  'kSchemaController',
  'kSchemaHeaders',
  'kSchemaParams',
  'kSchemaQuerystring',
  'kSchemaBody',
  'kSchemaResponse',
  'kSchemaErrorFormatter',
  'kSchemaVisited',
  'kRequest',
  'kRequestPayloadStream',
  'kRequestAcceptVersion',
  'kRequestCacheValidateFns',
  'kRequestContentType',
  'kRequestOriginalUrl',
  'kRequestSignal',
  'kRequestQuery',
  'kRequestQuerystring',
  'kHandlerTimeout',
  'kTimeoutTimer',
  'kOnAbort',
  'kFourOhFour',
  'kCanSetNotFoundHandler',
  'kFourOhFourLevelInstance',
  'kFourOhFourContext',
  'kDefaultJsonParse',
  'kReply',
  'kReplySerializer',
  'kReplyIsError',
  'kReplyHeaders',
  'kReplyTrailers',
  'kReplyHasStatusCode',
  'kReplyHijacked',
  'kReplyStartTime',
  'kReplyNextErrorHandler',
  'kReplyEndTime',
  'kReplyErrorHandlerCalled',
  'kReplyIsRunningOnErrorHook',
  'kReplySerializerDefault',
  'kReplyCacheSerializeFns',
  'kTestInternals',
  'kErrorHandler',
  'kErrorHandlerAlreadySet',
  'kChildLoggerFactory',
  'kHasBeenDecorated',
  'kKeepAliveConnections',
  'kRouteByXufa',
  'kLogController',
  'kDiagnosticsStore',
];

const symbols = {};
for (const name of names) symbols[name] = Symbol(`xufa.${name.slice(1, 2).toLowerCase()}${name.slice(2)}`);

module.exports = symbols;
