// The operators of conditions: the same symbols as Sequelize's (Symbol.for), so those of either package work.
const NAMES = [
  'eq',
  'ne',
  'gte',
  'gt',
  'lte',
  'lt',
  'not',
  'is',
  'in',
  'notIn',
  'like',
  'notLike',
  'iLike',
  'notILike',
  'startsWith',
  'endsWith',
  'substring',
  'regexp',
  'notRegexp',
  'iRegexp',
  'notIRegexp',
  'between',
  'notBetween',
  'overlap',
  'contains',
  'contained',
  'adjacent',
  'strictLeft',
  'strictRight',
  'noExtendRight',
  'noExtendLeft',
  'and',
  'or',
  'any',
  'all',
  'values',
  'col',
  'placeholder',
  'join',
  'match',
  'anyKeyExists',
  'allKeysExist',
];

const Op = Object.fromEntries(NAMES.map((name) => [name, Symbol.for(name)]));

module.exports = { Op };
